server:
  port: 8004
spring:
  application:
    name: config-server-techior
  profiles:
    active:
    - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prafulmeshram/proctor-config.git
          username: prafulmeshram
          password: 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
          clone-on-start: true
          default-label: master
        bootstrap: true
          