server:
  port: 8003
  
spring:
  profiles:
    active:
    #- native
    - git
  application:
    name: config-server  
  cloud:
    config:
      server:
#        native:
#          search-locations:
#          #- classpath:/config
#          - file:/home/jack/Documents/WORKSPACES/MSATER_MICROSERVICES/config 
        git:
          uri: https://github.com/prafulmeshram/master-microservice-config.git
          username: prafulmeshram
          password: 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
          clone-on-start: true
          default-label: master
        bootstrap: true
       